spring:
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/jtsys?useLegacyDatetimeCode=false&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2b8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      url: jdbc:mysql://localhost:3306/gw_game_ppc?useLegacyDatetimeCode=false&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2b8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20
      validation-query: SELECT 'x'
      validation-query-timeout: 30000
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000;druid.stat.logSlowSql=false
      use-global-data-source-stat: true
      reset-stat-enable: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: Abc_.123
        allow: 127.0.0.1,192.168.34.100
      #        deny: localhost
      aop-patterns: com..*.service.impl.*Impl.*(..)
      web-stat-filter:
        url-pattern: /*
        exclusions: '*.css,*.js,*.ico,*.png,*.jpg,*.gif,/druid/*'
        profile-enable: true



server:
  port: 8080

